baseurl: "/"
title: "Stackbit New Theme"
page_load_js: "assets/js/scripts.js"
params:
  description: An ultra customizable generic theme for Stackbit
  header:
    title: New Theme
    has_nav: true
    nav_links:
      - label: Features
        url: /features/
        type: link
      - label: Blog
        url: /blog/
        type: link
      - label: About
        url: /about/
        type: link
      - label: Style Guide
        url: /style-guide/
        type: link
  footer:
    has_nav: true
    nav_links:
      - label: Contact Us
        url: /contact/
        type: link
      - label: Privacy and Terms
        url: /terms/
        type: link
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/
        type: link
        new_window: true
      - label: GitHub
        url: https://github.com/
        type: link
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        type: link
        new_window: true
    content: "&copy; Stackbit-New. All rights reserved."
    links:
      - label: Made with Stackbit.
        url: https://www.stackbit.com
        type: link
        new_window: true
sass:
  input_file: sass/main.scss
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: compressed
  precision: 10